export const productPreviewData = [
  {
    name: "REDEEMED",
    title: "HOODIE",
    image: require('../../images/design-photos/redeemed-left.jpg'),
    price: "$35",
    index: 10,
  },
  {
    name: "ABIDE",
    title: "HOODIE",
    image: require('../../images/design-photos/abide-window.jpg'),
    price: "$45",
    index: 6,
  },
  {
    name: "HOPE",
    title: "LONGSLEEVE",
    image: require('../../images/design-photos/hope-longsleeve.jpg'),
    price: "$7",
    index: 5,
  },
  {
    name: "I AM THAT GIRL",
    title: "HAT",
    image: require('../../images/design-photos/girl-hat-top.jpg'),
    price: "$10",
    index: 4,
  },
  {
    name: "MACRON",
    title: "HOODIE",
    image: require('../../images/design-photos/macron-hoodie-guy.jpg'),
    price: "$35",
    index: 3,
  },
  {
    name: "BLESSED TO BLESS",
    title: "SHIRT",
    image: require('../../images/design-photos/blessed-horizontal.jpg'),
    price: "$10",
    index: 2,
  },
  {
    name: "BAY AREA",
    title: "LONG SLEEVE",
    image: require('../../images/design-photos/bay-area-main.jpg'),
    price: "$35",
    index: 1,
  },
  {
    name: "BERKELEY",
    title: "HOODIE",
    image: require('../../images/design-photos/berkeley-horizontal.jpg'),
    price: "$35",
    index: 0,
  },
  {
    name: "WALK ON WATER",
    title: "STICKER",
    image: require('../../images/design-photos/bottle-graphic.jpg'),
    price: "$3",
    index: 9,
  },
  {
    name: "SPERO BEAR",
    title: "STICKER",
    image: require('../../images/design-photos/bear-graphic.jpg'),
    price: "$3",
    index: 7,
  },
  {
    name: "MOUNTAIN MOVER",
    title: "STICKER",
    image: require('../../images/design-photos/mountain-graphic.jpg'),
    price: "$3",
    index: 8,
  },
  {
    name: "FALL 2021 PRODUCT",
    title: "CREWNECK",
    image: require('../../images/design-photos/abide-window.jpg'),
    price: "$35",
    index: 11,
  }
]